[package]
name = "mc-gen"
version = "0.1.0"
authors = ["Vincent Junge <jungevincent@gmail.com>"]
edition = "2018"
default-run = "test"

[profile.dev]
opt-level = 1

# For profiling
[profile.release]
debug = true

[dependencies]
anyhow = "1"
copy_dir = "0.1.2"
anvil-region = "0.8"
named-binary-tag = "0.6"
num-traits = "0.2"
num-derive = "0.2"
rayon = "1.4"
itertools = "0.9"
bresenham = { path = "bresenham-rs" }
hashlink = "0.6"
image = { version = "0.23", default-features = false, features = ["png"] } # Used only for debugging
hierarchical_pathfinding = "0.3.6"
hashbrown = "0.14.0"
# Turn off multithreading
bevy_ecs = {version = "0.11", default-features = false}
bevy_math = "0.11"
bevy_derive = "0.11.0"
bitflags = "2.3.3"
enum-iterator = "1.4.1"
nanorand = "0.7.0"

[patch.crates-io]
# Fix corruped gzip
named-binary-tag = { git = "https://github.com/SpecificProtagonist/named-binary-tag.git", branch = "fix-gzip" }
