[package]
name = "mc-gen"
version = "0.1.0"
authors = ["Vincent Junge <jungevincent@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
copy_dir = "0.1.2"
bimap = "0.5"
named-binary-tag = "0.2"
anvil-region = "0.3.2"
num-traits = "0.2"
num-derive = "0.2"