[package]
name = "mc-gen"
version = "0.1.0"
authors = ["Vincent Junge <jungevincent@gmail.com>"]
edition = "2021"
default-run = "test"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

# For profiling
[profile.release]
debug = true

[dependencies]
anyhow = "1"
copy_dir = "0.1.2"
anvil-region = "0.8"
named-binary-tag = "0.6"
num-traits = "0.2"
num-derive = "0.2"
rayon = "1.4"
itertools = "0.9"
bresenham = { path = "bresenham-rs" }
# Used only for debugging
image = { version = "0.23", default-features = false, features = ["png"] }
bevy_ecs = "0.13"
bevy_math = "0.13"
bevy_derive = "0.13"
bevy_utils = "0.13"
bitflags = "2.3.3"
enum-iterator = "1.4.1"
nanorand = {version = "0.8", git = "https://github.com/Absolucy/nanorand-rs.git" }
flate2 = "1"
