[package]
name = "mc-gen"
version = "0.1.0"
authors = ["Vincent Junge <jungevincent@gmail.com>"]
edition = "2018"

[profile.dev]
opt-level = 1
debug = 0

[profile.release]
lto = "thin"

[dependencies]
copy_dir = "0.1.2"
bimap = "0.5"
anvil-region = "0.4"
num-traits = "0.2"
num-derive = "0.2"
rand = "0.7.3"
rayon = "1.4"
itertools = "0.9"
bresenham = { path = "bresenham-rs" }
named-binary-tag = "0.3"
lazy_static = "1"
hashlink = "0.6"
image = { version = "0.23", default-features = false, features = ["png"] } # Used only for debugging
hierarchical_pathfinding = "0.3.6"